import type { Station } from "./types";

export const STATIONS: Station[] = [
  // 🔴 淡水信義線 (Tamsui-Xinyi Line)
  { id: "R28", name: "淡水", line: "淡水信義線" },
  { id: "R27", name: "紅樹林", line: "淡水信義線" },
  { id: "R26", name: "竹圍", line: "淡水信義線" },
  { id: "R25", name: "關渡", line: "淡水信義線" },
  { id: "R24", name: "忠義", line: "淡水信義線" },
  { id: "R23", name: "復興崗", line: "淡水信義線" },
  { id: "R22", name: "北投", line: "淡水信義線" },
  { id: "R22A", name: "新北投", line: "淡水信義線" },
  { id: "R21", name: "奇岩", line: "淡水信義線" },
  { id: "R20", name: "唭哩岸", line: "淡水信義線" },
  { id: "R19", name: "石牌", line: "淡水信義線" },
  { id: "R18", name: "明德", line: "淡水信義線" },
  { id: "R17", name: "芝山", line: "淡水信義線" },
  { id: "R16", name: "士林", line: "淡水信義線" },
  { id: "R15", name: "劍潭", line: "淡水信義線" },
  { id: "R14", name: "圓山", line: "淡水信義線" },
  { id: "R13", name: "民權西路", line: "淡水信義線" },
  { id: "R12", name: "雙連", line: "淡水信義線" },
  { id: "R11", name: "中山", line: "淡水信義線" },
  { id: "R10", name: "台北車站", line: "淡水信義線" },
  { id: "R09", name: "台大醫院", line: "淡水信義線" },
  { id: "R08", name: "中正紀念堂", line: "淡水信義線" },
  { id: "R07", name: "東門", line: "淡水信義線" },
  { id: "R06", name: "大安森林公園", line: "淡水信義線" },
  { id: "R05", name: "大安", line: "淡水信義線" },
  { id: "R04", name: "信義安和", line: "淡水信義線" },
  { id: "R03", name: "台北101/世貿", line: "淡水信義線" },
  { id: "R02", name: "象山", line: "淡水信義線" },

  // 🔵 板南線 (Bannan Line)
  { id: "BL23", name: "南港展覽館", line: "板南線" },
  { id: "BL22", name: "南港", line: "板南線" },
  { id: "BL21", name: "昆陽", line: "板南線" },
  { id: "BL20", name: "後山埤", line: "板南線" },
  { id: "BL19", name: "永春", line: "板南線" },
  { id: "BL18", name: "市政府", line: "板南線" },
  { id: "BL17", name: "國父紀念館", line: "板南線" },
  { id: "BL16", name: "忠孝敦化", line: "板南線" },
  { id: "BL15", name: "忠孝復興", line: "板南線" },
  { id: "BL14", name: "忠孝新生", line: "板南線" },
  { id: "BL13", name: "善導寺", line: "板南線" },
  { id: "BL12", name: "台北車站", line: "板南線" },
  { id: "BL11", name: "西門", line: "板南線" },
  { id: "BL10", name: "龍山寺", line: "板南線" },
  { id: "BL09", name: "江子翠", line: "板南線" },
  { id: "BL08", name: "新埔", line: "板南線" },
  { id: "BL07", name: "板橋", line: "板南線" },
  { id: "BL06", name: "府中", line: "板南線" },
  { id: "BL05", name: "亞東醫院", line: "板南線" },
  { id: "BL04", name: "海山", line: "板南線" },
  { id: "BL03", name: "土城", line: "板南線" },
  { id: "BL02", name: "永寧", line: "板南線" },
  { id: "BL01", name: "頂埔", line: "板南線" },

  // 🟢 松山新店線 (Songshan-Xindian Line)
  { id: "G19", name: "松山", line: "松山新店線" },
  { id: "G18", name: "南京三民", line: "松山新店線" },
  { id: "G17", name: "台北小巨蛋", line: "松山新店線" },
  { id: "G16", name: "南京復興", line: "松山新店線" },
  { id: "G15", name: "松江南京", line: "松山新店線" },
  { id: "G14", name: "中山", line: "松山新店線" },
  { id: "G13", name: "北門", line: "松山新店線" },
  { id: "G12", name: "西門", line: "松山新店線" },
  { id: "G11", name: "小南門", line: "松山新店線" },
  { id: "G10", name: "中正紀念堂", line: "松山新店線" },
  { id: "G09", name: "古亭", line: "松山新店線" },
  { id: "G08", name: "台電大樓", line: "松山新店線" },
  { id: "G07", name: "公館", line: "松山新店線" },
  { id: "G06", name: "萬隆", line: "松山新店線" },
  { id: "G05", name: "景美", line: "松山新店線" },
  { id: "G04", name: "大坪林", line: "松山新店線" },
  { id: "G03", name: "七張", line: "松山新店線" },
  { id: "G03A", name: "小碧潭", line: "松山新店線" },
  { id: "G02", name: "新店區公所", line: "松山新店線" },
  { id: "G01", name: "新店", line: "松山新店線" },

  // 🟡 中和新蘆線 (Zhonghe-Xinlu Line)
  { id: "O21", name: "迴龍", line: "中和新蘆線" },
  { id: "O20", name: "丹鳳", line: "中和新蘆線" },
  { id: "O19", name: "輔大", line: "中和新蘆線" },
  { id: "O18", name: "新莊", line: "中和新蘆線" },
  { id: "O17", name: "頭前庄", line: "中和新蘆線" },
  { id: "O16", name: "先嗇宮", line: "中和新蘆線" },
  { id: "O15", name: "三重", line: "中和新蘆線" },
  { id: "O14", name: "菜寮", line: "中和新蘆線" },
  { id: "O13", name: "台北橋", line: "中和新蘆線" },
  { id: "O12", name: "大橋頭", line: "中和新蘆線" },
  { id: "O11", name: "民權西路", line: "中和新蘆線" },
  { id: "O10", name: "中山國小", line: "中和新蘆線" },
  { id: "O09", name: "行天宮", line: "中和新蘆線" },
  { id: "O08", name: "松江南京", line: "中和新蘆線" },
  { id: "O07", name: "忠孝新生", line: "中和新蘆線" },
  { id: "O06", name: "東門", line: "中和新蘆線" },
  { id: "O05", name: "古亭", line: "中和新蘆線" },
  { id: "O04", name: "頂溪", line: "中和新蘆線" },
  { id: "O03", name: "永安市場", line: "中和新蘆線" },
  { id: "O02", name: "景安", line: "中和新蘆線" },
  { id: "O01", name: "南勢角", line: "中和新蘆線" },
  { id: "O54", name: "蘆洲", line: "中和新蘆線" },
  { id: "O53", name: "三民高中", line: "中和新蘆線" },
  { id: "O52", name: "徐匯中學", line: "中和新蘆線" },
  { id: "O51", name: "三和國中", line: "中和新蘆線" },
  { id: "O50", name: "三重國小", line: "中和新蘆線" },

  // 🟤 文湖線 (Wenhu Line)
  { id: "BR24", name: "南港展覽館", line: "文湖線" },
  { id: "BR23", name: "南港軟體園區", line: "文湖線" },
  { id: "BR22", name: "東湖", line: "文湖線" },
  { id: "BR21", name: "葫洲", line: "文湖線" },
  { id: "BR20", name: "大湖公園", line: "文湖線" },
  { id: "BR19", name: "內湖", line: "文湖線" },
  { id: "BR18", name: "文德", line: "文湖線" },
  { id: "BR17", name: "港墘", line: "文湖線" },
  { id: "BR16", name: "西湖", line: "文湖線" },
  { id: "BR15", name: "劍南路", line: "文湖線" },
  { id: "BR14", name: "大直", line: "文湖線" },
  { id: "BR13", name: "松山機場", line: "文湖線" },
  { id: "BR12", name: "中山國中", line: "文湖線" },
  { id: "BR11", name: "南京復興", line: "文湖線" },
  { id: "BR10", name: "忠孝復興", line: "文湖線" },
  { id: "BR09", name: "大安", line: "文湖線" },
  { id: "BR08", name: "科技大樓", line: "文湖線" },
  { id: "BR07", name: "六張犁", line: "文湖線" },
  { id: "BR06", name: "麟光", line: "文湖線" },
  { id: "BR05", name: "辛亥", line: "文湖線" },
  { id: "BR04", name: "萬芳醫院", line: "文湖線" },
  { id: "BR03", name: "萬芳社區", line: "文湖線" },
  { id: "BR02", name: "木柵", line: "文湖線" },
  { id: "BR01", name: "動物園", line: "文湖線" },
];
